version: "3.7"
services:
  mocker:
    build: ./mocker
    restart: always
    command: "./mocker config.json"
    volumes:
      - ./logs:/var/log
      - ./mocks:/mocks
    ports: 
      - 8081:1111
  editor:
    ports:
      - 8082:8000
    volumes:
      - ./mocks:/root
    command: "--root /root"
    image: coderaiser/cloudcmd